### ISSUE TITLE
create the zoo page

### ISSUE THREAD

**Issue by vitebo** [xaca/css_zoo#18]
I would like to create a page to display all animals, very similar to [emoji div](https://kimberrypi.github.io/emojidiv/)

Having all animals grouped on one page, we can even put the page on [github pages](https://pages.github.com/), this way anyone can view the zoo without having to clone the repository.

If you like the idea, I can work on it.

**Comment by xaca** [comment]
@vitebo Nice idea, I like it. Waiting for first version. :smiley: :100:

**Comment by vitebo** [comment]
all right i'll start working on it now

**Comment by xaca** [comment]
@vitebo Great! :muscle: :nerd_face:

**Comment by vitebo** [comment]
@xaca https://github.com/xaca/css_zoo/pull/46
I didn't really like my solution in this PR, but I've thought of something better
If you prefer just close this PR and I open another with the new solution. :smile:
